name: Bug Report
description: File a report to help us address an error
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report. Take your time and be as detailed as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: You can also mention what you expected to happen instead.
      placeholder: A clear and concise description of the bug
    validations:
      required: true
  - type: dropdown
    id: reproducible
    attributes:
      label: Reproducibility
      description: Is the bug reproducible?
      options:
        - Always
        - Sometimes
        - Random
        - Have Not Tried
        - Unable To Reproduce
        - N/A
    validations:
      required: true
  - type: dropdown
    id: operating
    attributes:
      label: What is the operating system you're encountering this issue on?
      multiple: false
      options:
        - Windows 7 x64
        - Windows 8
        - Windows 8 x64
        - Windows 10
        - Windows 10 x64
        - Windows 11        
        - MacOS
        - MacOS x64
        - Linux
        - Linux x64
    validations:
      required: true        
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: If applicable, describe the process of reproducing this bug.
      placeholder: 1. Open... 2. Click...
    validations:
      required: false
  - type: textarea
    id: adii
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
    validations:
      required: false
