blank_issues_enabled: false
contact_links:
    - name: Documentation Issue
      url: https://github.com/FINDarkside
      about: This issue tracker is not for documentation issues. Consider contacting us directly.
