name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build /p:Configuration=Release

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: DeveloperConsole
        path: ./DeveloperConsole/bin/Release/net6.0/DeveloperConsole.dll
        if-no-files-found: error
